<template>
    <div>
        <p>I'm just a sample component to investigate modal child components.</p>
        <p>{{id}}</p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque semper purus id cursus luctus. Sed sed diam aliquam, molestie nunc eu, interdum sapien. Nam pharetra molestie ultrices. Pellentesque et viverra sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id libero ipsum. Nam id dignissim nibh, vitae luctus metus. Fusce quis dignissim est. Vestibulum risus metus, congue ac lacinia vel, feugiat eu erat. Donec ac aliquam neque. Suspendisse sed condimentum augue, sed porttitor velit. Quisque ornare dolor quis diam aliquet, non gravida leo faucibus. Cras hendrerit mi et libero aliquam eleifend.
            Pellentesque aliquam non eros id sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque mattis metus nulla, eget molestie neque feugiat sit amet. Donec porta nibh eu accumsan ultrices. Quisque sed ipsum nisl. Fusce vulputate nulla imperdiet, mattis neque eget, venenatis odio. In rutrum nisl in lectus efficitur iaculis. Nam interdum felis auctor, aliquet justo in, ornare nisl. Proin at mauris dolor. Nunc ullamcorper nibh ac finibus condimentum. Suspendisse odio diam, aliquet vitae eros ut, tincidunt lobortis est.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc cursus auctor eros, id commodo metus. Duis varius ultrices velit, id pretium sapien semper eu. Nullam tristique est eu elit ultricies tempus. Donec mollis, metus sit amet ullamcorper mattis, purus ex accumsan tortor, eget suscipit lorem tortor placerat enim. Quisque sodales tristique leo, nec suscipit eros rhoncus sed. Aenean nec tempus augue, et elementum arcu. Fusce pulvinar metus urna, quis vehicula magna fringilla a. Aliquam viverra vulputate risus, sed consequat nulla placerat id. Suspendisse ultricies erat quis tincidunt efficitur. Donec at cursus ante.
            Morbi consequat mollis est, ut gravida risus eleifend dignissim. Aenean sodales iaculis pellentesque. Donec nec ex quis lectus faucibus efficitur. Nam cursus erat et urna bibendum, et sollicitudin est fringilla. Cras elementum lacus sit amet metus blandit, a efficitur enim hendrerit. Phasellus auctor massa vitae varius cursus. Maecenas in dui a turpis dapibus bibendum. Nunc et mollis sapien, vitae fermentum ex. Nam quis bibendum eros. Donec gravida tincidunt nulla, ac cursus lacus consequat nec.
            Nulla facilisi. Proin pellentesque consectetur purus, at aliquet dolor aliquam vel. Sed non tempor nibh, rutrum egestas sapien. Suspendisse vitae pretium elit. Proin placerat dolor eu ultricies dapibus. In at diam id velit condimentum blandit. Aenean tincidunt feugiat convallis.
            Pellentesque consectetur eros velit, sed consequat enim lobortis vitae. Morbi molestie malesuada dolor, vitae consectetur lacus pulvinar a. Nullam neque dui, ultrices eget ipsum id, aliquet tincidunt erat. Nulla facilisi. Quisque consectetur malesuada maximus. Cras ex mi, pharetra ac iaculis vestibulum, sollicitudin eget risus. Nulla auctor cursus suscipit. Quisque consequat mollis risus non euismod. Duis egestas nisl nec arcu condimentum efficitur. Nulla nulla orci, sagittis et mauris vitae, vehicula vehicula risus. Proin in dui arcu. Praesent interdum lacus sed enim sollicitudin, eget tincidunt nulla interdum.
            Maecenas pretium sem sit amet tortor imperdiet, sollicitudin dapibus arcu suscipit. Vivamus maximus aliquam enim, quis auctor nibh dictum dapibus. In venenatis purus eget nunc efficitur mollis a non tortor. Donec eleifend arcu sed lorem interdum interdum. Nunc sodales interdum nibh sed suscipit. Duis ultrices facilisis erat, sit amet cursus nulla elementum sagittis. Vivamus et enim nisi. Nulla varius fermentum ex, aliquet tristique nisi imperdiet id. In hac habitasse platea dictumst. Ut purus lorem, feugiat id porta vel, imperdiet eleifend enim. Mauris at massa arcu. Nam posuere justo eu est vestibulum, in commodo velit scelerisque. Cras feugiat rutrum neque eu scelerisque. Vestibulum laoreet est vel enim dictum rutrum. Integer molestie scelerisque commodo. Pellentesque at sodales diam.
            Proin consequat felis ipsum, nec interdum tellus sodales eu. Integer ullamcorper, elit eget faucibus aliquam, lectus nulla facilisis nulla, a euismod felis lectus ac nisi. Nam elementum sodales ultrices. Mauris fringilla ac neque a semper. Ut sodales nisl tortor, ut dapibus orci consectetur sed. Nunc rutrum ipsum tortor, et accumsan augue placerat sollicitudin. Curabitur nisi turpis, gravida vitae ex eu, ultricies aliquet neque. Vestibulum et mauris enim. Aenean ut rutrum neque, id fermentum purus. Sed ornare interdum tellus, eget mollis tellus vulputate nec. Fusce non dolor id orci placerat scelerisque quis nec diam. Fusce est nunc, maximus aliquet consequat ac, placerat non velit. Vivamus aliquet lacus nisl, a laoreet lorem bibendum vel.
            Nulla ullamcorper diam euismod lacus lobortis, id tempor nisl porttitor. Cras finibus commodo nunc in cursus. Vestibulum quis diam in arcu tincidunt rhoncus. Suspendisse placerat dui a facilisis finibus. Proin nec velit id felis sollicitudin ornare eu tempor odio. Sed faucibus quam ac lorem scelerisque imperdiet. Aenean dapibus facilisis lacus nec aliquet. Etiam ultrices ullamcorper sollicitudin. Proin hendrerit sapien sem, non sollicitudin ipsum lobortis quis. Suspendisse dapibus, justo vel pulvinar volutpat, erat erat sodales lacus, ac congue lacus metus nec nunc. Vestibulum hendrerit dui nibh, eget venenatis sapien egestas quis.
            Vivamus turpis augue, elementum non tristique non, tempor quis nisl. Quisque ut eros sodales, finibus enim in, tincidunt risus. Pellentesque pharetra nulla at justo rutrum efficitur. Etiam facilisis tellus porta ipsum imperdiet, a tincidunt neque tempor. Donec tincidunt aliquam felis a volutpat. Pellentesque tincidunt, nulla a fringilla laoreet, turpis nisi posuere nisi, et aliquet dui justo ut quam. In lacinia eget sem sed sollicitudin. Aliquam elit lacus, faucibus ut pellentesque sed, gravida at nisi. Vestibulum condimentum ipsum sit amet libero ultricies, eget bibendum sapien aliquam. Etiam vitae nunc massa. Quisque pellentesque eleifend leo ac cursus. Sed lacus enim, porta ac elementum id, maximus sit amet lectus. Sed dolor sem, finibus eu nisi vulputate, dapibus aliquet dolor. Mauris varius fringilla diam a varius.
            Vestibulum neque tellus, finibus et lacus vitae, tincidunt vestibulum mauris. Vivamus at ante sed nibh molestie convallis. Nunc vulputate turpis justo, nec sodales lectus iaculis sed. Vestibulum imperdiet felis vel dictum finibus. Aliquam rhoncus diam neque, vitae dignissim odio dictum ac. Maecenas in risus quam. Donec nibh libero, dignissim vel augue quis, vestibulum efficitur ex.
            In non ipsum id ipsum vestibulum tincidunt vitae quis ligula. Aliquam scelerisque tortor dui, eget tempus augue efficitur vitae. Aliquam porta pellentesque purus vel pharetra. Morbi sit amet nulla quis ipsum vestibulum ultrices. Nulla non turpis dolor. Maecenas sed fringilla eros. Sed id dapibus leo. Donec rhoncus magna nisl, nec dignissim enim consectetur quis.
            Nullam feugiat facilisis justo, nec pharetra sem scelerisque at. Nam tempus nec urna dapibus facilisis. Proin non dolor nisl. Nulla maximus blandit lectus, vel molestie nunc posuere ut. Suspendisse nec lacus tempor, aliquam massa at, blandit felis. Curabitur pellentesque euismod posuere. Phasellus sit amet justo maximus, dapibus lorem eget, fringilla ligula. Fusce porta purus in elementum molestie. Sed posuere consectetur mattis. Phasellus ullamcorper rhoncus imperdiet. Duis nec dignissim enim. Sed libero mauris, efficitur eget est quis, vestibulum vestibulum magna. Praesent rutrum odio id ligula sagittis mollis. Sed pretium, dolor sit amet lobortis ultrices, sapien quam rutrum nisi, at luctus nunc nisi aliquet est.
            Integer eget malesuada ex. Vestibulum commodo, arcu non accumsan tempus, augue felis pulvinar urna, nec cursus arcu augue volutpat dolor. Cras lobortis ligula eget neque ornare, cursus convallis risus finibus. Phasellus vitae quam ut tellus porttitor commodo. Etiam gravida ipsum a nulla euismod vehicula. Praesent scelerisque nisi in orci placerat tempus. Phasellus porta finibus nulla, sit amet dictum ipsum feugiat eget. Pellentesque vitae viverra metus. Morbi commodo nunc risus, a gravida mauris pellentesque vel. Pellentesque a metus quis lacus viverra euismod nec egestas quam. Mauris tempus commodo dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae porta arcu. Morbi dictum ipsum hendrerit est feugiat hendrerit.
            Ut placerat nunc at neque cursus molestie. Curabitur feugiat viverra orci, quis mattis ipsum finibus eget. Nam interdum nec lorem ac dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin at consequat diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aen
        </p>
    </div>
</template>

<script>
export default {
  name: 'sample-modal-child',
  props: ['id'],
  mounted() {
    // TODO for now this is set statically, but a real modal child would find its resource and then emit its title
    this.$emit('title-resolved', 'Sample Prompt Title #' + this.id);
  }
};
</script>

<style scoped>
</style>
