apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mwrite-peer-review-dev
    name: mwrite-peer-review-dev-api
    namespace: mwrite-peer-review-dev
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: mwrite-peer-review-dev
      deploymentconfig: mwrite-peer-review-dev-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}

