apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mwrite-peer-review-dev
    name: mwrite-peer-review-dev-frontend
    namespace: mwrite-peer-review-dev
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: mwrite-peer-review-dev
      deploymentconfig: mwrite-peer-review-dev-frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}

