apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: mwrite-peer-review-dev
  name: mwrite-peer-review-dev-api
  namespace: mwrite-peer-review-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mwrite-peer-review-dev-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: git@github.com:M-Write/mwrite-peer-review.git
      ref: develop
    sourceSecret:
      name: mwrite-peer-review-github-key
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: dockerfiles/api.Dockerfile
      from:
        kind: ImageStreamTag
        name: python:3-alpine
        namespace: mwrite-peer-review-dev
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
