# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('due_date_utc', models.DateTimeField(blank=True, null=True)),
                ('is_peer_review_assignment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'canvas_assignments',
            },
        ),
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'canvas_courses',
            },
        ),
        migrations.CreateModel(
            name='CanvasSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='peer_review.CanvasCourse')),
            ],
            options={
                'db_table': 'canvas_section',
            },
        ),
        migrations.CreateModel(
            name='CanvasStudent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('sortable_name', models.TextField()),
                ('username', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.CanvasCourse')),
                ('sections', models.ManyToManyField(blank=True, related_name='students', to='peer_review.CanvasSection')),
            ],
            options={
                'db_table': 'canvas_students',
            },
        ),
        migrations.CreateModel(
            name='CanvasSubmission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='canvas_submission_set', to='peer_review.CanvasAssignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peer_review.CanvasStudent')),
            ],
            options={
                'db_table': 'canvas_submissions',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'criteria',
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_reviews_for_student', to='peer_review.CanvasStudent')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_reviews_for_submission', to='peer_review.CanvasSubmission')),
            ],
            options={
                'db_table': 'peer_reviews',
            },
        ),
        migrations.CreateModel(
            name='PeerReviewComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('commented_at_utc', models.DateTimeField(blank=True, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peer_review.Criterion')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='peer_review.PeerReview')),
            ],
            options={
                'db_table': 'peer_review_comments',
            },
        ),
        migrations.CreateModel(
            name='PeerReviewDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_distribution_complete', models.BooleanField(default=False)),
                ('distributed_at_utc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peer_review_distributions',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('revision_fetch_complete', models.BooleanField(default=False)),
                ('peer_review_open_date_is_prompt_due_date', models.BooleanField(default=True)),
                ('peer_review_open_date', models.DateTimeField(blank=True, null=True)),
                ('distribute_peer_reviews_for_sections', models.BooleanField(default=False)),
                ('passback_assignment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_review', to='peer_review.CanvasAssignment')),
                ('reviewed_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_prompt', to='peer_review.CanvasAssignment')),
                ('revision_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_revision', to='peer_review.CanvasAssignment')),
                ('sections', models.ManyToManyField(blank=True, to='peer_review.CanvasSection')),
            ],
            options={
                'db_table': 'rubrics',
            },
        ),
        migrations.AddField(
            model_name='peerreviewdistribution',
            name='rubric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_review_distribution', to='peer_review.Rubric'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='criteria', to='peer_review.Rubric'),
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.CanvasCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewcomment',
            unique_together=set([('criterion', 'peer_review')]),
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together=set([('student', 'submission')]),
        ),
    ]
