# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('course_id', models.IntegerField()),
                ('due_date_utc', models.DateTimeField(blank=True, null=True)),
                ('is_peer_review_assignment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'canvas_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasStudent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('sortable_name', models.TextField()),
            ],
            options={
                'db_table': 'canvas_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasSubmission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'canvas_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'criteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'peer_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerReviewComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('commented_at_utc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peer_review_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerReviewDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_distribution_complete', models.BooleanField(default=False)),
                ('distributed_at_utc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peer_review_distributions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('revision_fetch_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rubrics',
                'managed': False,
            },
        ),
    ]
