# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='canvasstudent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='canvassubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peerreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peerreviewcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peerreviewdistribution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={},
        ),
    ]
