# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usefulness', models.IntegerField(choices=[(1, 'Very unuseful'), (2, 'Unuseful'), (3, 'Somewhat useful'), (4, 'Useful'), (5, 'Very useful')])),
                ('comment', models.TextField()),
                ('peer_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='peer_review.PeerReview')),
            ],
            options={
                'db_table': 'peer_review_evaluations',
            },
        ),
    ]
