# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0002_peerreviewevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewevaluation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
