# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0002_auto_20170721_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstudent',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvassubmission',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='canvas_submission_set', to='peer_review.CanvasAssignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canvassubmission',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='peer_review.CanvasStudent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterion',
            name='rubric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='criteria', to='peer_review.Rubric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreview',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_reviews_for_student', to='peer_review.CanvasStudent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreview',
            name='submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_reviews_for_submission', to='peer_review.CanvasSubmission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='criterion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='peer_review.Criterion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='peer_review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='peer_review.PeerReview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewdistribution',
            name='rubric',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peer_review_distribution', to='peer_review.Rubric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='passback_assignment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_review', to='peer_review.CanvasAssignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='reviewed_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_prompt', to='peer_review.CanvasAssignment'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='revision_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubric_for_revision', to='peer_review.CanvasAssignment'),
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together=set([('student', 'submission')]),
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewcomment',
            unique_together=set([('criterion', 'peer_review')]),
        ),
    ]
