# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0003_auto_20170721_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'canvas_courses',
            },
        ),
        migrations.CreateModel(
            name='CanvasSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='peer_review.CanvasCourse')),
            ],
            options={
                'db_table': 'canvas_section',
            },
        ),
        migrations.RemoveField(
            model_name='canvasstudent',
            name='section',
        ),
        migrations.AddField(
            model_name='canvasstudent',
            name='section',
            field=models.ManyToManyField(blank=True, to='peer_review.CanvasSection'),
        ),
    ]
