# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0004_auto_20170721_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstudent',
            name='username',
            field=models.TextField(default='changeme'),
            preserve_default=False,
        ),
    ]
