# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 15:20
from __future__ import unicode_literals

from django.db import migrations


def single_course_to_multiple_courses(apps, schema_editor):
    CanvasStudent = apps.get_model('peer_review', 'CanvasStudent')
    for student in CanvasStudent.objects.all():
        student.courses.add(student.course)


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0004_canvasstudent_courses'),
    ]

    operations = [
        migrations.RunPython(single_course_to_multiple_courses)
    ]
