# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0005_auto_20180607_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasstudent',
            name='course',
        ),
    ]
