# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0005_canvasstudent_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasstudent',
            old_name='section',
            new_name='sections',
        ),
    ]
