# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0006_auto_20170721_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasassignment',
            name='course_id',
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='peer_review.CanvasCourse'),
            preserve_default=False,
        ),
    ]
