# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0007_auto_20180816_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('weekday', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'job_log',
            },
        ),
        migrations.AlterField(
            model_name='rubric',
            name='peer_review_evaluation_is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
