# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0007_auto_20170726_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvassection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.CanvasCourse'),
        ),
    ]
