# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0008_auto_20180816_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='peer_review_evaluation_due_date',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='peer_review_evaluation_is_mandatory',
        ),
    ]
