# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0008_auto_20181203_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
