# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0008_auto_20170726_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='peer_review_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='peer_review_open_date_is_prompt_due_date',
            field=models.BooleanField(default=True),
        ),
    ]
