# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-02-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0009_auto_20181203_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreviewcomment',
            name='edited_at_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
