# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0009_auto_20170802_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='distribute_peer_reviews_for_sections',
            field=models.BooleanField(default=False),
        ),
    ]
