# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0010_rubric_distribute_peer_reviews_for_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='sections',
            field=models.ManyToManyField(blank=True, to='peer_review.CanvasSection'),
        ),
    ]
