# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-02-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0010_add_edit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewcomment',
            name='commented_at_utc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewcomment',
            name='edited_at_utc',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
