# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0012_auto_20170804_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvassection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='peer_review.CanvasCourse'),
        ),
    ]
