apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: mwrite-peer-review-dev
  name: mwrite-peer-review-dev-frontend
  namespace: mwrite-peer-review-dev 
spec:
  lookupPolicy:
    local: false

