apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: mwrite-peer-review-dev 
  name: python
  namespace: mwrite-peer-review-dev 
spec:
  dockerImageRepository: "docker.io/python"
  lookupPolicy:
    local: false

